echo "hai nt shafivulla"
echo "this is my project"
echo "this new process"
echo "please do this project"
echo "this new compliment"
echo "this is new administrator"
echo "new attachment"
echo "new entity"
echo "hello shafivulla"
echo "create new repo"
echo "new commit"
echo "new present"

