echo "hello eliyas"
echo "hai imran"
echo "hai malik"
echo "create new reposatory"
echo "hello shafi"
echo "hai shafi"
echo "data stracture"
echo "new program"
echo "new para and new commit explain"
echo "new profit"
