echo "this is new command"
echo "new motivation"
echo "data structure concept"
echo "creat dbms concept"
echo "the new explanations"
echo "more iterations"
echo "new culture"
echo "new friends"
echo "creat new repo"
echo "the file changes"
echo "new advance"
echo "new project"
